### ISSUE TITLE
[BUG] Compress doesn't work with SSR

### ISSUE THREAD

**Issue by StefanoSega** [rse/graphql-query-compress#10]
I implemented an application that consume a graphql API and use GQC to compress the query ... everything works perfectly.

Unfortunately the server side rendering crashes with the error:
```
{ Error: Cannot find module 'tokenizr'
[0]     at o (webpack:///./node_modules/graphql-query-compress/lib/graphql-query-compress.node.js?:25:268)
[0]     at eval (webpack:///./node_modules/graphql-query-compress/lib/graphql-query-compress.node.js?:25:425)
[0]     at Object.1.tokenizr (webpack:///./node_modules/graphql-query-compress/lib/graphql-query-compress.node.js?:28:40)
[0]     at o (webpack:///./node_modules/graphql-query-compress/lib/graphql-query-compress.node.js?:25:374)
[0]     at r (webpack:///./node_modules/graphql-query-compress/lib/graphql-query-compress.node.js?:25:540)
[0]     at eval (webpack:///./node_modules/graphql-query-compress/lib/graphql-query-compress.node.js?:25:569)
[0]     at eval (webpack:///./node_modules/graphql-query-compress/lib/graphql-query-compress.node.js?:25:38)
[0]     at eval (webpack:///./node_modules/graphql-query-compress/lib/graphql-query-compress.node.js?:25:59)
[0]     at Object../node_modules/graphql-query-compress/lib/graphql-query-compress.node.js (/Users/stefanosaga/Documents/projects/yoda-ui/ui/dist/__server__/0.ssr.js:400:1)
[0]     at __webpack_require__ (/Users/stefanosaga/Documents/projects/yoda-ui/ui/dist/__server__/ssr.js:690:30) code: 'MODULE_NOT_FOUND' }
[0] (node:37388) UnhandledPromiseRejectionWarning: Error: Error: Cannot find module 'tokenizr'
[0]     at errorLoading (webpack:///./react/routes.jsx?:10:9)
[0] (node:37388) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[0] (node:37388) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I tried installing `tokenizr` and even including it in the webpack entries for the SSR bundle, but it doesn't work and it cannot find Tokenizr.

**Comment by rse** [comment]
Well, seems like your Webpack instance does not honor the "browser" entry in package.json of graphql-query-compress, as it uses the Node.js variant which has Tokenizr not built-in but in an external dependency. Try loading "graphql-query-compress/lib/graphql-query-compress.browser.js" instead of "graphql-query-compress" as a work-around.

**Comment by StefanoSega** [comment]
Yep, solved!
Thanks a lot

**Comment by benjaminpearson** [comment]
Thanks for this library @rse! Just wanted to flag that I also ran into this issue when using the library in a NextJS project. Do you think there might be a way to solve this as part of the library code or adding a note to the README?
